[package]
name = "voxbirch_py"
version = "0.1.0"
edition = "2024"

[lib]
name = "vb_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28.0", features = ["extension-module"] }
voxbirch= { path = "../" }