[package]
name = "voxbirch_py"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]
name = "voxbirch"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28.0", features = ["extension-module"] }
wincode = "0.2.5"
serde = "1.0.228"
wincode-derive = "0.2.3"
voxbirch= { path = "../" }
